# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-28 13:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('url_shortner', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='web_url',
            name='count',
            field=models.IntegerField(default=0),
        ),
    ]
