# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-28 13:17
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('url_shortner', '0002_web_url_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='web_url',
            name='url',
            field=models.TextField(validators=[django.core.validators.URLValidator()]),
        ),
    ]
